#include "builder.h"
#include "guild.h"
#include "token.h"
#include "market.h"
#include "color.h"
#include "player.h"
#include "game.h"
#include "second_token.h"
#include "second_builder.h"
#include <stdio.h>
#include <stdlib.h>